# conda env create -f environment.yml
name: base
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - numpy
  - numba
  - pandas
  - scipy
  - rasterio
  - tqdm
  - typed-ast
  - jupyterlab
  - ipywidgets
  - ipykernel
  - matplotlib
  - statsmodels
  - cxx-compiler
  - pip
  - pip:
    - /usr/local/rdblib-2.4.1-x86_64-linux/interface/python/riegl.rdb-2.4.1-cp34.cp35.cp36.cp37.cp38.cp39.cp310-none-linux_x86_64.whl
    - -e .
variables:
  RIVLIB_ROOT: /usr/local/rivlib-2_6_0-x86_64-linux-gcc9
  RDBLIB_ROOT: /usr/local/rdblib-2.4.1-x86_64-linux
  PYLIDAR_CXX_FLAGS: -std=c++11 
